### ISSUE TITLE
Loci Submodule in Other Codes

### ISSUE THREAD

**Issue by rlfontenot** [EdwardALuke/loci#31]
This feature will take the work from CFD Research;s #6 (dev) and enable Loci being built/configured as a submodule of other codes, such as Loci/CHEM and Loci/GGFS (and others). This feature is related to #20.

**Comment by rlfontenot** [comment]
With some detective work, we were able to do this purely on the Loci/GGFS and Loci/CHEM side without modifications to Loci. Future issues can readd spotless/etc make directives, but as it stands no modifications need to be made in Loci for it to properly submodule into either of the Loci codes.

**Comment by TimothyEDawson** [comment]
@EdwardALuke 

Seems we celebrated a bit too soon - We are having issues in GGFS with the preprocessor directives in src/include/Loci.h which appear to be an old workaround for some MPI implementations placing "Map" in the global namespace. It traces back to this change from 2005: https://github.com/rlfontenot/loci/commit/c023e76a48d50ce5ca291a8ed07a27bdd9e18156

It seems to me that turning "Map" into a macro which is replaced by "Loci::Map" is a potentially dangerous workaround, as it's a pretty common term (e.g. it's used extensively in the Eigen library).

We haven't had any issues internally simply commenting out the preprocessor directives, and uncommenting the original `using Loci::Map;` line. This might not be a safe fix to commit back to Loci as the referenced MPI implementations causing the original issue could still be around, but it has also been 19 years so perhaps that's no longer a concern. I'll look into workarounds on the GGFS side, but I'd appreciate your thoughts on whether this should be altered on the Loci side.

**Comment by EdwardALuke** [comment]
I think it is pretty safe to get rid of that code.  That was a problem with
an early version of C++ bindings for MPI that have since been deprecated
(and removed I believe)  . I am pretty sure that this is no longer a
problem.  BTW, if you want to use Loci and avoid this problem just #include
<Loci> instead of <Loci.h>  This includes everything but keeps it in the
Loci namespace.  Then you can decide exactly what wants to be pulled into
the Loci namespace. Loci.h is just a convenience header for novice users.
I think it would be a good idea to remove the #define,  If loci compiles on
relatively modern openMPI and MPICH versions of MPI then I think it should
be good.

- Ed
